version: '3.8'

services:
  app:
    build: .
    container_name: backend_app
    ports:
      - "8000:8000"
    volumes:
      # - db_data:/app/data
      # - ./data:/app/data
      - ./static:/app/app/static
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:password@db:3306/mydatabase
      - PYTHONPATH=/app
    networks:
      - backend_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: inspection_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # 這一行讓 MySQL 的 3306 端口對外暴露
    networks:
      - backend_network
    restart: unless-stopped
    depends_on:
      - test

  test:
    build: .
    container_name: backend_test
    # volumes:
      # - .:/app
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - PYTHONPATH=/app
    command: pytest app/tests/ -v

networks:
  backend_network:
    driver: bridge
volumes:
  mysql_data: